#
# zshell config file
#

# env
export MY_CONFIG_PATH=$HOME/.local/config
export PATH=$HOME/.local/bin:$PATH

# alias
alias config="cd ${MY_CONFIG_PATH}"
if [[ -n $(command -v nvim) ]]; then 
	alias vim="nvim"
fi

# plugin: powerlevel10k
source $HOME/.p10k.zsh
source $MY_CONFIG_PATH/zshell/powerlevel10k/powerlevel10k.zsh-theme

# plugin: zsh-autosuggestions
source $MY_CONFIG_PATH/zshell/zsh-autosuggestions/zsh-autosuggestions.zsh

# plugin: zsh-syntax-highlighting (must be at the end of zshrc file)
source $MY_CONFIG_PATH/zshell/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
